README.md

Je me permet de rajouter mes vidéos devops qui sont sur la chaine inpulse.tv 😸

Ajout playlist devops de inpulse.tv

---

conteneur-orchestration/README.md

Docker Swarm reste dans la course face à K8s pour les plus petites organisations (hors SaaS), même s'il permet moins de souplesse, il reste beaucoup plus simple
- Docker Swarm
- Outil UI de gestion (Portainer.io par exemple)

Orchestrateurs : proposition de Docker Swarm

---

README.md

Il y a eu une petite disparation, je rajoute ^^'

Reajout inpulse.tv

---

conteneur-orchestration/README.md

* Ajout sites K8S (doc / blog)

Ajout sites K8S

---

.github/workflows/main.yml

* Ajout d'un nom sur le pipe line du fichier Readme

Add Name for GH Actions workflow

---

README.md

Blog: mcorbin
Communautes: SRE France
Youtube: Devoxx FR
Podcast: Message a caractere informatique
Section tutorials

Ajout 1 blog, 1 commu, 1 YT, 1 podcast et creation section tuto

---

README.md

Ajout d'un lien vers le discord Dev'Obs

ajout(Communautés): DevObs discord

---

README.md

Ajout du blog de la société bearstech.
Les thèmes du blogs : Performance, sécurité devops et d'exploitation cloud computing.

add socity blog : bearstech

---

README.md

Merci pour ce repo !
Voici une PR pour ajouter le PodCast Electro Monkeys et corriger une typo :)

[Podcasts] Ajout electro monkeys + typo

---

surveillance/README.md

Ne pas le faire correctement entraînera simplement la fermeture cette demande

ajout zabbix

---

.github/pull_request_template.md

Ne pas le faire correctement entraînera simplement la fermeture cette demande

correction

---

README.md

Ne pas le faire correctement entraînera simplement la fermeture cette demande

clarification des règles

---

.github/issue_template.md
.github/pull_request_template.md

Ne pas le faire correctement entraînera simplement la fermeture cette demande

commit initial

---

README.md

ajout lien issue et pr

---

.github/ISSUE_TEMPLATE/1-ajout-lien.md

ajout icone

---

README.md

Modification introduction

---

README.md

correction coquille

---

surveillance/README.md

ajout proposition opentelemetry

---

reseau-securite/README.md

Je propose d'ajouter le nom de l'auteur "Tanenbaum", car quand on évoque la référence en réseau & télécom, on parle souvent "du Tanenbaum".

ajout du nom de l'auteur Tanenbaum qui est en tant que tel le terme utilisé pour décrire cette référence. 

---

README.md
admin-serveurs/README.md

https://blog.microlinux.fr/
https://www.editions-eyrolles.com/Livre/9782212677386/administration-linux-par-la-pratique
https://www.editions-eyrolles.com/Livre/9782212679496/administration-linux-par-la-pratique-tome-2
https://wiki.archlinux.org/title/Main_page_(Fran%C3%A7ais)
Kiki Novak a récemment remis à zéro son site et remet à jours tout les articles qui le composait.
Les anciens articles restent visibles [ICI](https://archives.microlinux.fr/). Pour savoir le pourquoi de cette remise à zero c'est par [là](https://blog.microlinux.fr/archivage-du-blog/).
Les livres traitent de l'administration Linux depuis un niveau débutant à un niveau avancé (beaucoup de Centos et un peu de OpenSUSE Leap. …

Ajout livres Kiki Novak + site de sa société MicroLinux + Wiki Archlinux fr

---

README.md

Deux modifications : 
- ajout de liens vers le site et la chaine Youtube de FranceDevOps
- ajout d'un lien vers un article de blog de @ggraveaud sur l'étude DevOps - Accelerate. 

Ajout infos FranceDevOps + blog Accelerate

---

README.md

Remplacement du lien entreprise vers lien blog de l'entreprise

Maj URL blog pour un lien entrerprise

---

README.md

modification structure

---

infra-as-code/README.md

https://netflix.github.io/chaosmonkey/
https://medium.com/@crochefolle/ingénierie-du-chaos-chaos-engineering-in-french-ea17310c8824
https://medium.com/paris-chaos-engineering-community/ingénierie-du-chaos-chaos-engineering-in-french-partie-2-où-en-sommes-nous-8e899e519832
https://www.youtube.com/watch?v=zM5KE1DC9U0&t=159s
Chaos Monkey est un logiciel conçu par Netflix pour tester la résilience de ses infrastructures informatiques. 
ou des ressources …

Ajout du Chaos Monkey

---

configuration-serveurs/README.md

ajout video xavki  postgre

---

README.md
admin-serveurs/README.md
ci-cd/README.md
conteneur-orchestration/README.md
langages-programmation/README.md
surveillance/README.md

ajout playlists xavki

---

conteneur-orchestration/README.md

- Lien sur les traductions de la doc Kubernetes en français
- Le forum Kubernetes (en anglais), avec une section "Regional", où la section "France" reste à créer
- Le Wiki Kubernetes hébergé par SFEIR, très complet et en français

Ajout ressources Kubernetes

---

configuration-serveurs/README.md

PostgreSQL - Architecture et notions avancées
Très bonne doc sur le fonctionnement et l'admin avancée de PostgreSQL, difficilement trouvable en ligne. M'a rendu de grands services lorsque mon équipe a eu à gérer des instances de PostgreSQL sous fortes contraintes.

PostgreSQL Admin

---

README.md
admin-serveurs/README.md
cloud/README.md
configuration-serveurs/README.md
conteneur-orchestration/README.md
infra-as-code/README.md
langages-programmation/README.md

ajout livrs

---

README.md
conteneur-orchestration/README.md

ajout podman + liens

---

README.md

erreur typo

---

conteneur-orchestration/README.md

Ajout lien podman

---

surveillance/README.md

* Ajout liens datadog
* Ajout liens splunk

Ajout liens

---

cloud/README.md

* Mauvais Lien Azure chez AWS
* Correction autre lien

Mauvais Lien Azure chez AWS, correction lien

---

README.md

ajout enix + plusieurs chaines youtube

---

README.md

ajout cocadmin

---

conteneur-orchestration/README.md

ajout video aurélie vache

---

README.md

Correction d'une petite typo sur le nom de Limawi (pas de "n" final).

Petite typo sur Limawi

---

admin-serveurs/README.md
ci-cd/README.md
cloud/README.md
configuration-serveurs/README.md
conteneur-orchestration/README.md
infra-as-code/README.md
langages-programmation/README.md
reseau-securite/README.md
surveillance/README.md

Ajout livres gratuits riptutorial

---

README.md

ajout jpetazzo

---

conteneur-orchestration/README.md

ajout de bcp de liens

---

ci-cd/README.md

ajout molecule

---

README.md

ajout april

---

ci-cd/README.md
infra-as-code/README.md

ajout lien formatux

---

README.md

ajout export feedly

---

README.md

ajout blog soat

---

README.md
feedly.opml

- [Blog](https://thebidouilleur.xyz/blog)
- [Wiki](https://thebidouilleur.xyz/docs/intro/)
Je n'ai que quelques visites mensuelles mais je tente quand même d'ajouter mon blog dans la liste. J'écris régulièrement des docs sur les sujets que j'aborde dans mon apprentissage personnel. Terraform, Packer, Kubernetes (depuis peu), Nix sont des sujets que j'essaye d'approfondir sur mon site. 
Mon contenu est majoritairement français mais je profite de la fonctionnalité i18n de Docusaurus pour traduire les pages les plus importantes en Anglais.
ou des …

ajout du site thebidouilleur.xyz

---

langages-programmation/README.md

**None**
**Le lien du livre gratuit Apprenez Rust est dans la section 2. Golang au lieu de la section 3. Rust**

Correction du lien Apprenez Rust

---

README.md

ajout lien conférences

---

README.md

ajout soutien

---

ci-cd/README.md
infra-as-code/README.md
langages-programmation/README.md

ajout multiple lien jenkins, puppet et video rust

---

infra-as-code/README.md

ajout lien chef

---

langages-programmation/README.md

**Vidéo youtube parlons peu, parlons rust**
**Vidéo en français sur rust. Introduction au langage.**

Ajout de parlons peu, parlons rust

---

README.md
infra-as-code/README.md

ajout 2 bogs

---

conteneur-orchestration/README.md

** https://www.ssi.gouv.fr/uploads/2020/12/docker_fiche_technique.pdf **
** Recommentations sur la sécurité des conteneurs docker réalisé par l'ANSSI en 2020, il montre les bonnes pratiques à avoir lors d'un déploiement Docker**
** https://devopssec.fr/article/cours-complet-apprendre-technologie-docker#begin-article-section **
** MOOC simple et complet pour découvrir Docker. Une bonne alternatives à OCR **
** https://www.youtube.com/playlist?list=PL8SZiccjllt1jz9DsD4MPYbbiGOR_FYHu ** 
** Série de 8 Vidéos sur l'utilisation de Docker et Compose, quelques astuces sympa. Un format un peux plus court, divertissant pour commencer Docker **
** https://www.youtube.com/watch?v=8VAYSn2DmJM **
** Parceque Docker c'est pas que sur Linux, il existe aussi des Solutions pour Mac et Windows bien …

🐳 Prosposition d'améliorations

---

README.md
conteneur-orchestration/README.md

- [Twitter](https://twitter.com/TheBidouilleur)
- [ Docker avec une tasse de café ](https://docker.avec.une-tasse-de.cafe/)
Je propose l'ajout de mon Twitter ainsi que d'une présentation intéractive pour apprendre Docker. (L'idée est de permettre aux débutants d'avoir un getting-started simple et détaillant chaque étape). 

Ajout du site docker.avec.une-tasse-de.cafe et Twitter TheBidouilleur

---

configuration-serveurs/README.md

pas mal de liens

---

README.md

**https://github.com/scraly/developers-conferences-agenda**
**La page n'est pas spécialement en français (ni en anglais d'ailleurs, sauf l'introduction), c'est une liste de conf avec des dates**

Ajout de scraly/developers-conferences-agenda

---

README.md

**[Blog SOAT](https://blog.soat.fr/)**
**Sur l'interface Github sans le https, la redirection ne fonctionne pas. Je propose de l'ajouter pour du confort.**

Fix : ajout http sur un lien SOAT (pour éviter un bug de redirection)

---

README.md

ajout mastodon

---

README.md

ajout chaine naitech

---

README.md

correction toc

---

surveillance/README.md

Ajout de https://www.dynatrace.com/ et de https://newrelic.com/
Ainsi que leur blog
https://www.dynatrace.com/
https://newrelic.com/
J'ai proposé l'ajout de la partie "Tracing" sous "Surveillance. en effet le "tracing est considéré comme le 3 eme piller de l' [Observability
](https://en.wikipedia.org/wiki/Observability). 
J'ai mis 2 outils très connus pour faire le tracing d'application, Dynatrace et New Relic.
A noter aussi que "Datadog" dispose de très bonnes features de tracing aussi. Comme datadog est déjà dans la partie logging je ne l'ai pas ajouté.
URL des sites …

Ajout de la partie Tracing sous Surveillance

---

README.md

ajout filador

---

README.md
infra-as-code/README.md

Lien : [Automatisation : de Python à Ansible](https://pressbooks.pub/automatisation/)
Nous avons écrit ce livre en 2017, nous avons souhaité pouvoir partager avec le plus grand nombre ce mini guide pour débuter avec Python et Ansible sur l'automatisation. Nous l'avons voulu gratuit et en français en essayant de le rendre le plus accessible pour des débutants. Nous avons le sentiment de nous inscrire dans la même logique que ce repo et c'est pour ça que nous déposons cette pull request, pour continuer à partager notre passion au plus grand nombre.
ou …

Ajout du livre https://automatisation.pressbooks.pub - Automatisation : de Python à Ansible

---

ci-cd/README.md

**https://gitlab.com/r2devops/hub**
**Bibliothèque de templates de pipeline CI/CD pour gitlab. Découvert lors d'une présentation au Devops D DAY 2022**

Ajout hub templates CICD Gitlab (r2devops.io)

---

admin-serveurs/README.md

**http://aral.iut-rodez.fr/fr/sanchis/enseignement/bash/**
**Il s'agit d'un cours régulièrement mis à jour, dont je me sers pour créer les miens. La vision universitaire complete les autres liens, même si les fondamentaux et la démarche sont similaire.** 

Ajout de l'Introduction à la programmation en Bash de Eric Sanchis

---

reseau-securite/README.md

chore: ajout sécurité

---

README.md

- https://www.vrchr.fr/
Blog perso, avec qq news tech en FR.

feat: add @rverchere blog

---

conteneur-orchestration/README.md

* https://mickael-baron.fr/slides/soa/introduction-docker
* https://mickael-baron.fr/soa/microservices-mise-en-oeuvre-kubernetes
* https://github.com/mickaelbaron/microservices-kubernetes-gettingstarted-tutorial
Les ressources à ajouter sont utilisées dans le cadre d'enseignement que je dispense à l'Université de Poitiers et à l'ISAE-ENSMA. Il y a deux supports de cours et un tutoriel. Pour le support de cours sur Docker, j'ai focalisé sur le pourquoi et ensuite le comment. Il y a moins de technique, mais c'était voulu pour que les étudiants comprennent l'intérêt de Docker. Il y a aussi des animations Asciinema pour rendre la présentation plus interactive.
URL des …

Ajout des supports de cours (Docker et Kubernetes) de Mickaël BARON

---

README.md

chore: ajout bog antoine mayer

---

README.md

ajout Stéphane Philippart

---

README.md

**L'URL du blog de Stéphane Philippart est : https://philippart-s.github.io/blog/**
**Correction de l'URL du blog de Stéphane Philippart**

fix: Correction du lien vers le blog de Stéphane Philippart

---

README.md

chore: ajout cockpit.io

---

README.md

chore: ajout le chalet

---

README.md

chore: Ajout chaine youtube confs

---

README.md

[chaîne KCD France](https://www.youtube.com/@KubernetesCommunityDaysFr)
Ajout de la chaine des Kubernetes Community Days France.   
Etant une conférence sur les technologies Cloud Native et DevOps en Français je pense qu'elle trouve toute ca place ici.
La première édition c'est déroulé plus tôt cette année.

Ajout de la chaine youtube KCD France

---

README.md

fix: correction du titre des videos de confs

---

ci-cd/README.md

fix: correction lien r2devops

---

README.md
cloud/README.md

chore: ajout

---

cloud/README.md

chore: ajour guna

---

README.md

fix: ajout olivier poncet

---

cloud/README.md

**[blog](https://woivre.fr)**
**Ajout du blog de Wilfried Woivré qui est un MVP français sur la partie Azure**

Ajout du blog de Wilfried Woivré - https://woivre.fr

---

README.md

chore: add wiki-tech

---

README.md

iMil, est un Ops qui fait du Dev système :)
* [Emile `iMil' Heitor](https://www.youtube.com/channel/UCqGZmYTiWmOl7vXb0XBbY_Q)
iMil est un Ops qui fait du Dev système. Il partage en live sur twich et redif sur YT
Noter ses playlists principales :
- Linux (vraiment) from Scratch
- NetBSD from Scratch
- C from Scratch
- Rust from Scratch

Ajout de la chaine YT d'iMil

---

README.md

Fix de la typo dans la table des matières 

Typo dans le lien twitch de la table des matières

---

README.md
feedly.opml

Suite à mon changement de domaine et de générateur de site, voici la nouvelle URL et le nouveau fichier RSS.

Mise à jour URL : TheBidouilleur -> Une tasse de café

---

README.md

ajout lien
